name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JRE 8 as libs for R8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: adopt-hotspot

      - name: Set up JDK 14 for build
        uses: actions/setup-java@v3
        with:
          java-version: 14
          distribution: adopt-hotspot

      - name: Build & test the agent standalone
        run: ./gradlew quickTest

      - name: Build & test the full distributable
        run: ./gradlew distTest

      - uses: actions/upload-artifact@v4
        with:
          name: distributables
          path: build/libs/*-dist.jar
          if-no-files-found: error

      - name: Publish tagged release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*-dist.jar
          file_glob: true
          tag: ${{ github.ref }}